# Generated by Django 5.0.6 on 2024-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('max_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'unique_together': {('station_id', 'date')},
            },
        ),
    ]
